// This file is automatically generated. Manual changes add project-specific configuration.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { env } from '@/lib/env';

const missingConfigMessage = 'Supabase environment variables are not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to your environment to enable Supabase-powered features.';

export const isSupabaseConfigured = Boolean(env.supabase);

const createMissingClient = (): SupabaseClient<Database> => new Proxy({} as SupabaseClient<Database>, {
  get: () => {
    throw new Error(missingConfigMessage);
  },
});

const browserStorage = typeof window === 'undefined' ? undefined : window.localStorage;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = env.supabase
  ? createClient<Database>(env.supabase.url, env.supabase.anonKey, {
    auth: {
      storage: browserStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  })
  : createMissingClient();

export const SUPABASE_MISSING_CONFIG_MESSAGE = missingConfigMessage;